/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.awt.GridLayout;
import javax.swing.JFrame;
import VIEW.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author NUPSI 04
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        URL url = this.getClass().getResource("/VIEW/imagem/Icone.jpg");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JLabel();
        btnAssistencia = new javax.swing.JLabel();
        btnSobre = new javax.swing.JLabel();
        btnSair = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 228, 229));

        btnClientes.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagem/64cliente.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClientesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnClientesMouseReleased(evt);
            }
        });

        btnAssistencia.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAssistencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAssistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagem/64assistencia.png"))); // NOI18N
        btnAssistencia.setText("Assintência");
        btnAssistencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAssistencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAssistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAssistenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAssistenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAssistenciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAssistenciaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAssistenciaMouseReleased(evt);
            }
        });

        btnSobre.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnSobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagem/64sobre.png"))); // NOI18N
        btnSobre.setText("Sobre");
        btnSobre.setToolTipText("");
        btnSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSobre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSobreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSobreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSobreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSobreMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSobreMouseReleased(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagem/64exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSairMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSairMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssistencia, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnAssistencia)
                .addGap(20, 20, 20)
                .addComponent(btnSobre)
                .addGap(20, 20, 20)
                .addComponent(btnSair)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        pnl2.setBackground(new java.awt.Color(249, 249, 249));
        pnl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1061, Short.MAX_VALUE)
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja Sair ?");
            if(confirma == 0){
                this.dispose();
            }else{
                
            }
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
    ClienteView cliente = new ClienteView();
    cliente.setLocation(pnl2.getWidth()/2 - cliente.getWidth()/2,pnl2.getHeight()/2 - cliente.getHeight()/2);
    pnl2.removeAll();
    pnl2.updateUI();
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnAssistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssistenciaMouseClicked
    AssistenciaView assistencia = new AssistenciaView(0);
    pnl2.removeAll();
    pnl2.updateUI();
    }//GEN-LAST:event_btnAssistenciaMouseClicked

    private void pnl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl2MouseClicked
        pnl2.requestFocusInWindow();
    }//GEN-LAST:event_pnl2MouseClicked

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        btnClientes.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        btnClientes.setForeground(Color.black);
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMousePressed
        btnClientes.setForeground(Color.lightGray);
    }//GEN-LAST:event_btnClientesMousePressed

    private void btnClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseReleased
        btnClientes.setForeground(Color.black);
    }//GEN-LAST:event_btnClientesMouseReleased

    private void btnAssistenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssistenciaMouseEntered
        btnAssistencia.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnAssistenciaMouseEntered

    private void btnAssistenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssistenciaMouseExited
        btnAssistencia.setForeground(Color.black);
    }//GEN-LAST:event_btnAssistenciaMouseExited

    private void btnAssistenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssistenciaMousePressed
        btnAssistencia.setForeground(Color.lightGray);
    }//GEN-LAST:event_btnAssistenciaMousePressed

    private void btnAssistenciaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssistenciaMouseReleased
        btnAssistencia.setForeground(Color.black);
    }//GEN-LAST:event_btnAssistenciaMouseReleased

    private void btnSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseClicked
        SobreView sobre = new SobreView();
        pnl2.removeAll();
        pnl2.updateUI();
    }//GEN-LAST:event_btnSobreMouseClicked

    private void btnSobreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseEntered
        btnSobre.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnSobreMouseEntered

    private void btnSobreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseExited
        btnSobre.setForeground(Color.black);
    }//GEN-LAST:event_btnSobreMouseExited

    private void btnSobreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMousePressed
        btnSobre.setForeground(Color.lightGray);
    }//GEN-LAST:event_btnSobreMousePressed

    private void btnSobreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseReleased
        btnSobre.setForeground(Color.black);
    }//GEN-LAST:event_btnSobreMouseReleased

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        btnSair.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
        btnSair.setForeground(Color.black);
    }//GEN-LAST:event_btnSairMouseExited

    private void btnSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMousePressed
        btnSair.setForeground(Color.lightGray);
    }//GEN-LAST:event_btnSairMousePressed

    private void btnSairMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseReleased
        btnSair.setForeground(Color.black);
    }//GEN-LAST:event_btnSairMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAssistencia;
    private javax.swing.JLabel btnClientes;
    private javax.swing.JLabel btnSair;
    private javax.swing.JLabel btnSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnl2;
    // End of variables declaration//GEN-END:variables
}
